import os
import uuid
from typing import Annotated, Optional

from fastapi import Depends, FastAPI, Response
from fastapi.security import APIKeyCookie
from perfact.dbschematools import patch
from sqlmodel import Session, create_engine, func, not_, or_, select, update

from .appuser import AppUser, AppUserLogin

COOKIE = "__user_cookie"

app = FastAPI()
engine = create_engine("postgresql+psycopg://zope@/perfactema")
patch(f"{os.path.dirname(__file__)}/schema")


def get_session():
    with Session(engine) as session:
        yield session
        session.commit()


LoginCookieDep = Annotated[
    str,
    Depends(
        APIKeyCookie(name=COOKIE, description="Generated by /login", auto_error=False)
    ),
]
SessionDep = Annotated[Session, Depends(get_session)]


def process_auth(
    session: SessionDep, cookie: LoginCookieDep, response: Response
) -> Optional[AppUser]:
    """
    Process authorization at the beginning of (essentially) every request.
    Compare user cookie against appuserlogin_cookie and appuserlogin_nextcookie.
    If the user sent nextcookie, rotate them (assuming that from now on the old
    cookie will no longer be sent). In any case, set the cookie to be used in
    the future in the response (there was something about browsers sometimes no
    longer sending a cookie if we don't remind them with every request that
    this cookie is to be set).
    """
    stmt = select(AppUserLogin).where(
        or_(
            AppUserLogin.appuserlogin_cookie == cookie,
            AppUserLogin.appuserlogin_nextcookie == cookie,
        ),
        not_(AppUserLogin.appuserlogin_done),
    )
    login: Optional[AppUserLogin] = session.scalars(stmt).one_or_none()
    if not login:
        return
    send_cookie = login.appuserlogin_nextcookie or login.appuserlogin_cookie
    user = login.user
    if cookie == login.appuserlogin_nextcookie:
        login.appuserlogin_cookie = login.appuserlogin_nextcookie
        login.appuserlogin_nextcookie = None
        # We commit here, so the authentication phase and the payload phase are
        # done in separate transactions.
        session.commit()

    response.set_cookie(
        key=COOKIE,
        value=send_cookie,
        httponly=True,
        secure=True,
        samesite="strict",
    )
    return user


Auth = Annotated[Optional[AppUser], Depends(process_auth)]


@app.put("/admin/generate_user")
async def generate_user(username: str, password: str, session: SessionDep):
    """
    We would not actually allow this, at least not without first checking elevated
    permissions
    """
    user: AppUser = AppUser(
        appuser_name=username,
        appuser_password=AppUser.encrypt_pw(password),
    )
    session.add(user)
    return {"success": True}


@app.post("/admin/rotate_cookies")
async def rotate_cookies(session: SessionDep):
    """
    Something that would usually rather be done periodically and can not be triggered
    manually.
    """
    session.execute(
        update(AppUserLogin)
        .where(not_(AppUserLogin.appuserlogin_done))
        .values(appuserlogin_nextcookie=func.uuidv4())
    )


@app.post("/login")
async def login(username: str, password: str, session: SessionDep, response: Response):
    stmt = select(AppUser).where(AppUser.appuser_name == username)
    user: AppUser = session.exec(stmt).one_or_none()
    if not user or not user.verify_pw(password):
        return {"success": False}
    login = AppUserLogin(
        appuserlogin_appuser_id=user.appuser_id,
        appuserlogin_cookie=uuid.uuid4(),
    )
    session.add(login)
    response.set_cookie(
        key=COOKIE,
        value=login.appuserlogin_cookie,
        httponly=True,
        secure=True,
        samesite="strict",
    )
    return {
        "success": True,
    }


@app.post("/logout")
async def logout(
    session: SessionDep, cookie: LoginCookieDep, response: Response
) -> None:
    stmt = select(AppUserLogin).where(AppUserLogin.appuserlogin_cookie == cookie)
    login: AppUserLogin = session.scalars(stmt).one_or_none()
    if login:
        login.appuserlogin_done = True
    response.delete_cookie(COOKIE)


@app.get("/username")
async def username(session: SessionDep, user: Auth) -> Optional[str]:
    if user:
        return user.appuser_name
