import inspect
from dataclasses import dataclass
from functools import wraps
from typing import Annotated, Callable, Optional, TypeVar

from fastapi import Depends, HTTPException, Query, Response, status
from fastapi.routing import APIRoute
from fastapi.security import APIKeyCookie, APIKeyHeader
from pydantic import BaseModel, Field
from sqlalchemy import any_, not_, or_, select, text
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.responses import JSONResponse

from .dbsession import DBSession
from .model import (
    AppStc_Paths,
    AppUser,
    AppUserKey,
    AppUserLogin,
    AppUserXStc,
)

COOKIE = "__user_cookie"

LoginCookieDep = Annotated[
    str,
    Depends(
        APIKeyCookie(name=COOKIE, description="Generated by /login", auto_error=False)
    ),
]
ApikeyHeaderDep = Annotated[
    str,
    Depends(APIKeyHeader(name="Authorization", auto_error=False)),
]


class ContextParams(BaseModel):
    appstc_id: Optional[int] = Field(default=None, alias="__appstc_id")


ContextParamsDep = Annotated[ContextParams, Query()]


@dataclass
class AuthInfo:
    """
    Authentication information for the current user
    """

    name: str
    roles: list[str]


def _auth_apikey(session: DBSession, key: str) -> Optional[AppUser]:
    """
    Split provided Apikey on first dash. The first part is an identifier so we only
    check keys in the database that have the same initial part.
    The rest is checked against the hashed value in the database.
    """
    if not key.startswith("Apikey "):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid authorization header",
        )
    return AppUserKey.find(session, key.split()[1])


def _auth_cookie(
    session: DBSession, cookie: str, response: Response
) -> Optional[AppUser]:
    """
    Compare user cookie against appuserlogin_cookie and appuserlogin_nextcookie.
    If the user sent nextcookie, rotate them (assuming that from now on the old
    cookie will no longer be sent). In any case, set the cookie to be used in
    the future in the response (there was something about browsers sometimes no
    longer sending a cookie if we don't remind them with every request that
    this cookie is to be set).
    """
    row = session.execute(
        select(AppUserLogin, AppUser)
        .join_from(AppUserLogin, AppUser)
        .where(
            or_(
                AppUserLogin.cookie == cookie,
                AppUserLogin.nextcookie == cookie,
            ),
            not_(AppUserLogin.done),
        )
    ).first()
    if not row:
        return None
    login, user = row

    send_cookie = login.nextcookie or login.cookie
    if cookie == login.nextcookie:
        login.cookie = login.nextcookie
        login.nextcookie = None

    response.set_cookie(
        key=COOKIE,
        value=send_cookie,
        httponly=True,
        secure=True,
        samesite="strict",
    )
    return user


def _process_auth(
    session: DBSession,
    cookie: LoginCookieDep,
    apikey: ApikeyHeaderDep,
    params: ContextParamsDep,
    response: Response,
) -> Optional[AuthInfo]:
    """
    Process authorization at the beginning of (essentially) every request.
    (If a path does not depend on Auth, it is accessible anonymously)
    1) Check for user using either a login cookie or an API key
    2) Check appstc (organization area). If an appstc_id is provided, check that the
       user is allowed to activate it. Otherwise select a default appstc
    3) Check which roles the user has in this appstc
    """
    appuser = None
    if apikey is not None:
        appuser = _auth_apikey(session, apikey)
    elif cookie is not None:
        appuser = _auth_cookie(session, cookie, response)

    if not appuser:
        return None

    # Check for appstc
    appstc_id = params.appstc_id
    if appstc_id:
        if not session.execute(
            select(
                select(1)
                .select_from(AppUserXStc)
                .join(AppStc_Paths, AppUserXStc.appstc_id == any_(AppStc_Paths.id_path))
                .where(AppStc_Paths.id == appstc_id)
                .where(AppUserXStc.appuser_id == appuser.id)
                .exists()
            )
        ).scalar():
            appstc_id = None
    else:
        # Find the "first" appstc for the user
        appstc_id = session.execute(
            select(AppUserXStc.appstc_id)
            .join(AppStc_Paths, AppUserXStc.appstc_id == AppStc_Paths.id)
            .where(AppUserXStc.appuser_id == appuser.id)
            .order_by(AppStc_Paths.depth, AppStc_Paths.id_path)
            .limit(1)
        ).scalar()

    roles: list[str] = []
    if appstc_id:
        rows = session.execute(
            text(
                """
                select
                  array_agg(appgroup_zoperole)
                from appgroup
                join apppermxgroup
                  on apppermxgroup_appgroup_id = appgroup_id
                join appuserxperm
                  on appuserxperm_appperm_id = apppermxgroup_appperm_id
                 and appuserxperm_appuser_id = :appuser_id
                join apppermxstc
                  on apppermxstc_appperm_id = apppermxgroup_appperm_id
                join appstc_paths
                  on apppermxstc_appstc_id = any(id_path)
                 and id = :appstc_id
                """
            ),
            {
                "appuser_id": appuser.id,
                "appstc_id": appstc_id,
            },
        ).all()
        roles = rows[0][0] or []

    result = AuthInfo(name=appuser.name, roles=roles)
    # We commit here, so the authentication phase and the payload phase are
    # done in separate transactions.
    session.commit()
    return result


Auth = Annotated[Optional[AuthInfo], Depends(_process_auth)]


_F = TypeVar("_F", bound=Callable[..., object])


def require_roles(*roles: str) -> Callable[[_F], _F]:
    """
    Decorator to check for given roles
    """

    def require(required: tuple[str, ...]):

        def checker(user: Auth):
            # Check if all required scopes are present
            roles = set() if user is None else user.roles
            missing = set(required) - set(roles)
            if missing:
                raise HTTPException(
                    status_code=403,
                    detail={
                        "msg": "Missing required permissions",
                        "missing": list(missing),
                    },
                )

            return True

        return checker

    dep = Depends(require(roles))

    def decorator(func: _F) -> _F:
        sig = inspect.signature(func)

        # create a new parameter for the dependency (keyword-only)
        dep_param = inspect.Parameter(
            "scope_check",
            kind=inspect.Parameter.KEYWORD_ONLY,
            annotation=Annotated[None, dep],
        )

        # build new signature: keep original params, append dep_param
        params = list(sig.parameters.values()) + [dep_param]
        new_sig = sig.replace(parameters=params)

        @wraps(func)
        async def wrapper(*args, **kwargs):
            # remove scope_check if present before calling original func
            kwargs.pop("scope_check", None)
            return await func(*args, **kwargs)

        # attach the new signature so FastAPI sees the dependency
        wrapper.__signature__ = new_sig  # type: ignore
        # Inject OpenAPI metadata
        wrapper.__dict__["required_roles"] = roles
        return wrapper  # type: ignore

    return decorator


def add_403_to_openapi(app):
    """
    Call this after all routes are added.
    """
    for route in app.routes:
        if isinstance(route, APIRoute):
            endpoint = route.endpoint
            roles = getattr(endpoint, "required_roles", None)
            if roles:
                # Add 403 response if not already present
                route.responses.setdefault(
                    403,
                    {
                        "description": "Forbidden – missing required permissions",
                        "model": list[str],
                    },
                )


class SameSitePostMiddleware(BaseHTTPMiddleware):
    """
    Rejects all POST/PUT/PATCH requests that do not include a valid
    Sec-Fetch-Site header. Allowed values: "same-origin"
    """

    async def dispatch(self, request, call_next):
        if request.method in ("POST", "PUT", "PATCH"):
            sec_fetch_site = request.headers.get("sec-fetch-site")

            if sec_fetch_site != "same-origin":
                return JSONResponse(
                    status_code=401,
                    content={"detail": f"Unauthorized: cross-site {request.method}"},
                )

        return await call_next(request)
